@baseUrl = http://localhost:4000
@validUserId = timpet3

### GET all users
GET {{baseUrl}}/api/users

### GET testuser with name testuser1
GET {{baseUrl}}/api/users/{{validUserId}}

### PATCH a user
PATCH {{baseUrl}}/api/users/{{validUserId}}
Content-Type: application/json

{
  "playlists": [
    {
      "id": "0",
      "description": "jkndkewjnd",
      "title": "Testplaylist 1",
      "tracks": [
        {
          "id": "0",
          "name": "Castle of glass",
          "artist": "Linkin Park"
        }
      ]
    },
    {
      "description": "jkndkewjnd",
      "title": "Testplaylist 2",
      "id": "1",
      "tracks": [
        {
          "id": "1",
          "name": "One more light",
          "artist": "Linkin Park"
        }
      ]
    }
  ]
}
### Create a new user
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "_id": "timpet4",
  "name": "timpeFour"
}